config/routes.rb
Rails.application.routes.draw do
  resources :markers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marker.rb
class Marker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  def index
    @markers = Marker.all
    @client = @client = GooglePlaces::Client.new(ENV['GOOGLE_MAPS_API_KEY'])
    @spots = @client.spots(-33.8670522, 151.1957362, :types => 'school')

  end

  def new
    @marker = Marker.new
  end

  def create
    @marker = Marker.new(marker_params)
    if @marker.save
      redirect_to markers_path
    else
      render :new
    end
  end

  private
  def marker_params
    params.require(:marker).permit(:name, :latitude, :longitude)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpookyMap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markers/_form.html.erb
<%= form_for @marker do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name  %>
  <%= f.label :latitude %>
  <%= f.number_field :latitude, step: :any  %>
  <%= f.label :longitude %>
  <%= f.number_field :longitude, step: :any %>
  <%= f.submit %>
<% end %>

app/views/markers/index.html.erb
<h3>My Google Maps Demo</h3>
<div id="map"></div>

<%= javascript_tag do %>
  var markers = <%= raw @markers.to_json %>;
<% end %>
<br>
<hr>
<br>
<%= link_to "Add A Marker", new_marker_path %>

<script async defer
src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap">
</script>
<br>
<hr>
  
<br>
<hr>
<% @spots.each do |spot| %>
<p><%= spot.name %></p>
<% end %>

app/views/markers/new.html.erb
<h1>Add Marker</h1>

<%= render('form') %>